#!/usr/bin/env bash
# Rebuild Buildoto.app from source and drop it into /Applications, unsigned.
#
# Why: ElectronAsarIntegrity in Info.plist cryptographically pins the SHA256
# of the packaged ASAR. Hot-patching the installed app.asar is rejected at
# relaunch, so every code iteration needs a fresh build where electron-builder
# regenerates the hash. This script is the shortest path from source change
# to running app (~20-25s on a warm cache, no signing, no notarize).
#
# Usage:
#   ./scripts/install-local.sh
#
# Notes:
# - We use `--mac --dir` (not DMG) to skip the disk-image packaging step.
# - Quarantine xattrs are cleared so Gatekeeper lets the unsigned binary run.
# - The `Buildoto.app` path is resolved from package.json's version.

set -euo pipefail

cd "$(dirname "$0")/.."

# shellcheck disable=SC2155
VERSION="$(node -p "require('./package.json').version")"
# electron-builder picks the arch from the host when `--mac --dir` is used.
ARCH="$(uname -m)"
case "$ARCH" in
  arm64) BUILDER_ARCH="mac-arm64" ;;
  x86_64) BUILDER_ARCH="mac" ;;
  *) echo "unsupported arch: $ARCH" >&2; exit 2 ;;
esac

BUILT_APP="release/${VERSION}/${BUILDER_ARCH}/Buildoto.app"
TARGET_APP="/Applications/Buildoto.app"

echo "→ pnpm build"
pnpm build

echo "→ electron-builder --mac --dir (unsigned)"
pnpm exec electron-builder --mac --dir

if [[ ! -d "$BUILT_APP" ]]; then
  echo "build did not produce $BUILT_APP" >&2
  ls -la "release/${VERSION}/" >&2 || true
  exit 3
fi

echo "→ killing running Buildoto (if any)"
pkill -x Buildoto 2>/dev/null || true
# Small nap so the OS releases file locks on /Applications/Buildoto.app.
sleep 1

echo "→ installing to $TARGET_APP"
rm -rf "$TARGET_APP"
cp -R "$BUILT_APP" "$TARGET_APP"
xattr -rd com.apple.quarantine "$TARGET_APP" 2>/dev/null || true

echo "→ done."
echo "   Launch:   open '$TARGET_APP'"
echo "   ASAR hash was regenerated by electron-builder (ElectronAsarIntegrity valid)."
